- src/main/java/com/programmers/dev/kream/product/domain/Brand.java
- src/main/java/com/programmers/dev/kream/product/domain/Product.java
- src/main/java/com/programmers/dev/kream/product/domain/ProductInfo.java
- src/main/java/com/programmers/dev/kream/product/domain/SizedProduct.java
> Feat: 상품 엔티티 구현 [#3]

- src/main/java/com/programmers/dev/kream/product/domain/BrandRepository.java
- src/main/java/com/programmers/dev/kream/product/domain/ProductRepository.java
- src/main/java/com/programmers/dev/kream/product/domain/SizedProductRepository.java
- src/main/java/com/programmers/dev/kream/user/domain/UserRepository.java
> Feat: Repository 구현

- src/main/java/com/programmers/dev/kream/product/application/SizedProductService.java
- src/main/java/com/programmers/dev/kream/product/domain/Brand.java
- src/main/java/com/programmers/dev/kream/product/domain/Product.java
- src/main/java/com/programmers/dev/kream/product/domain/ProductInfo.java
- src/main/java/com/programmers/dev/kream/product/domain/SizedProduct.java
- src/main/java/com/programmers/dev/kream/product/domain/SizedProductRepository.java
- src/main/java/com/programmers/dev/kream/product/ui/GetProductInfoResponse.java
- src/main/java/com/programmers/dev/kream/product/ui/SizedProductController.java
- src/test/java/com/programmers/dev/kream/product/application/SizedProductServiceTest.java
- src/test/java/com/programmers/dev/kream/product/ui/SizedProductControllerTest.java
- src/test/resources/application.yml
1. 테스트 환경 분리 
2. 상품 조회 로직 구현 
[안내 사항] 
- main에 있는 sql 파일에 의해서 test 코드에 영향이 가는 것을 확인했습니다. 
- 이를 방지하고자 환경 분리를 진행했습니다. 
- 티켓 단위가 잘못 끊어져서 feature 브랜치에 좀 맞지 않게 구현이 되었지만 참고 부탁드립니다. 
- 테스트 코드 
- 현재 별도의 Exception Handler가 없기 때문에 상세한 에러 처리보다는 Optional로 반환하는 로직으로 구현했습니다.
> 상품 조회 로직 구현 

- src/main/java/com/programmers/dev/kream/product/application/BrandService.java
- src/main/java/com/programmers/dev/kream/product/application/ProductService.java
- src/main/java/com/programmers/dev/kream/product/application/SizedProductService.java
- src/main/java/com/programmers/dev/kream/product/domain/Brand.java
- src/main/java/com/programmers/dev/kream/product/domain/BrandRepository.java
- src/main/java/com/programmers/dev/kream/product/domain/Product.java
- src/main/java/com/programmers/dev/kream/product/domain/ProductInfo.java
- src/main/java/com/programmers/dev/kream/product/domain/ProductRepository.java
- src/main/java/com/programmers/dev/kream/product/domain/SizedProduct.java
- src/main/java/com/programmers/dev/kream/product/ui/ProductUpdateRequest.java
- src/test/java/com/programmers/dev/kream/product/application/BrandServiceTest.java
- src/test/java/com/programmers/dev/kream/product/application/ProductServiceTest.java
- src/test/java/com/programmers/dev/kream/product/application/SizedProductServiceTest.java
SizedProduct, Product, Brand CRUD 기능 구현 및 테스트 코드 작성하였습니다.
> Feat: 상품 CRUD 기능 구현 [#11]

- src/main/java/com/programmers/dev/kream/sellbidding/application/SellBiddingService.java
- src/main/java/com/programmers/dev/kream/sellbidding/domain/SellBidding.java
- src/main/java/com/programmers/dev/kream/sellbidding/domain/SellBiddingRepository.java
- src/main/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingController.java
- src/main/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingRequest.java
- src/main/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingResponse.java
- src/main/java/com/programmers/dev/kream/user/domain/Address.java
- src/main/java/com/programmers/dev/kream/user/domain/User.java
- src/test/java/com/programmers/dev/kream/sellbidding/application/SellBiddingServiceTest.java
- src/test/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingControllerTest.java
판매 입찰 등록 
> 현재 회원의 로그인 기능을 어떻게 할 지 정해지지 않았기에 1차적으로 query parameter로 받아오게끔 구현했습니다. 
> 이 부분 관련해서는 토론을 해서 공통화 시켜야 할 것 같네요. 
> 개인적으로는 Cookie 를 사용해도 좋을 것 같습니다. 
> 예외를 던지지 않고 구현을 하려고 했지만 코드가 너무 복잡해지는 것 때문에 기본 예외를 던지고 있습니다. 
> 이 부분은 토론 후 공통 예외 클래스 만들면 좋을 것 같아요.
> Feature: 판매자 입찰 등록 구현 [#20]

- src/main/java/com/programmers/dev/kream/purchasebidding/domain/PurchaseBidding.java
- src/main/java/com/programmers/dev/kream/purchasebidding/domain/PurchaseBiddingRepository.java
- src/main/java/com/programmers/dev/kream/sellbidding/application/SellBiddingService.java
- src/main/java/com/programmers/dev/kream/sellbidding/domain/SellBiddingRepository.java
- src/main/java/com/programmers/dev/kream/sellbidding/ui/ProductInformation.java
- src/main/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingController.java
- src/main/java/com/programmers/dev/kream/sellbidding/ui/SizeInformation.java
- src/test/java/com/programmers/dev/kream/sellbidding/application/SellBiddingServiceTest.java
- src/test/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingControllerTest.java
- 크림에서 판매를 하려고할 때 정보 조회가 가능한 API 구현
--- 
- 현재 DataBase구조를 바꾸기로 했기 때문에 쿼리 부분은 간단하게 구현했습니다.
> Feat: 페이지 조회 기능 구현 [#9]

- src/main/java/com/programmers/dev/kream/product/application/BrandService.java
- src/main/java/com/programmers/dev/kream/product/application/ProductService.java
- src/main/java/com/programmers/dev/kream/product/application/SizedProductService.java
- src/main/java/com/programmers/dev/kream/product/domain/Product.java
- src/main/java/com/programmers/dev/kream/product/domain/ProductInfo.java
- src/main/java/com/programmers/dev/kream/product/domain/SizedProductRepository.java
- src/main/java/com/programmers/dev/kream/product/ui/BrandController.java
- src/main/java/com/programmers/dev/kream/product/ui/ProductController.java
- src/main/java/com/programmers/dev/kream/product/ui/SizedProductController.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/BrandResponse.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/BrandSaveRequest.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/BrandsGetResponse.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/GetProductInfoResponse.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/ListResponse.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/ProductResponse.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/ProductSaveRequest.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/ProductUpdateRequest.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/ProductsGetResponse.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/SizedProductResponse.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/SizedProductSaveRequest.java
- src/test/java/com/programmers/dev/kream/product/application/BrandServiceTest.java
- src/test/java/com/programmers/dev/kream/product/application/ProductServiceTest.java
- src/test/java/com/programmers/dev/kream/product/application/SizedProductServiceTest.java
- src/test/java/com/programmers/dev/kream/product/ui/BrandControllerTest.java
- src/test/java/com/programmers/dev/kream/product/ui/ProductControllerTest.java
- src/test/java/com/programmers/dev/kream/product/ui/SizedProductControllerTest.java
- 코드리뷰 반영 및 도메인별 등록 수정 삭제 조회 기능을 수행하는 컨트롤러를 구현하였습니다.
- 컨트롤러 테스트 코드 작성을 직접 해보는것은 처음이라 검토 부탁드립니다.
--- 
- SizedProductController, SizedProductService는 2차스프린트때 삭제할 예정이기 때문에 추가적인 수정을 하지는 않았습니다.
- rebase는 이번 커밋이 approve될지 안될지 모르기때문에 approve가 된다면 하겠습니다.
> Feat: Controller 구현 [#24]

- src/main/java/com/programmers/dev/kream/exception/CreamException.java
- src/main/java/com/programmers/dev/kream/exception/CreamExceptionHandler.java
- src/main/java/com/programmers/dev/kream/exception/ErrorCode.java
- src/main/java/com/programmers/dev/kream/exception/ErrorResponse.java
- 공통 예외 담당 클래스 생성
- ErrorCode의 경우 Enum으로 생성
- Handler에서 Exception처리. 
- 공통된 응답을 내려주기 위해 code, description만 사용했습니다.
> Feat: 예외 공통화 처리 [#36]

- src/main/java/com/programmers/dev/kream/sellbidding/application/SellBiddingService.java
- src/main/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingController.java
- src/test/java/com/programmers/dev/kream/sellbidding/application/SellBiddingServiceTest.java
- src/test/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingControllerTest.java
- 주석 제거 
- 도메인의 경우 오해의 소지가 있어 주석을 나뒀습니다. 
- 거래 성사 시 송금 로직 추가
> Refactor sell

- build.gradle
- src/docs/asciidoc/api/purchasebidding/purchase-bid-select-view.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/com/programmers/dev/kream/purchasebidding/application/PurchaseBiddingService.java
- src/test/java/com/programmers/dev/kream/purchasebidding/ui/PurchaseBiddingControllerTest.java
구매입찰 시 사이즈 선택 화면에 관련된 코드를 수정했습니다.
> Purchase restdocs

- src/docs/asciidoc/index.adoc
- src/main/java/com/programmers/dev/kream/product/application/BrandService.java
- src/main/java/com/programmers/dev/kream/product/application/ProductService.java
- src/main/java/com/programmers/dev/kream/product/application/SizedProductService.java
- src/test/java/com/programmers/dev/kream/product/application/BrandServiceTest.java
- src/test/java/com/programmers/dev/kream/product/application/ProductServiceTest.java
- src/test/java/com/programmers/dev/kream/product/application/SizedProductServiceTest.java
- src/test/java/com/programmers/dev/kream/product/ui/BrandControllerTest.java
- src/test/java/com/programmers/dev/kream/product/ui/ProductControllerTest.java
- src/test/java/com/programmers/dev/kream/product/ui/SizedProductControllerTest.java
1️⃣ 상품 도메인에 관련된 API 명세회 작업을 하였습니다.
2️⃣ EntityNotFoundException을 공통 예외인 CreamException으로 변경하였습니다.
> Product API 명세화 & 예외 변경

- src/test/java/com/programmers/dev/kream/sellbidding/application/SellBiddingServiceTest.java
- src/test/java/com/programmers/dev/kream/sellbidding/ui/SellBiddingControllerTest.java
SizedProduct 엔티티 삭제로 인한 테스트 코드 오류 부분 수정
> Test: SizedProduct 제거로 인한 테스트 코드 수정 [#52]

- build.gradle
- src/main/java/com/programmers/dev/kream/common/jwt/JwtAccessDeniedHandler.java
- src/main/java/com/programmers/dev/kream/common/jwt/JwtAuthentication.java
- src/main/java/com/programmers/dev/kream/common/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/com/programmers/dev/kream/common/jwt/JwtAuthenticationFilter.java
- src/main/java/com/programmers/dev/kream/common/jwt/JwtAuthenticationProvider.java
- src/main/java/com/programmers/dev/kream/common/jwt/JwtAuthenticationToken.java
- src/main/java/com/programmers/dev/kream/common/jwt/JwtConfigure.java
- src/main/java/com/programmers/dev/kream/common/jwt/JwtTokenUtils.java
- src/main/java/com/programmers/dev/kream/configuration/SecurityConfiguration.java
- src/main/java/com/programmers/dev/kream/exception/ErrorCode.java
- src/main/java/com/programmers/dev/kream/user/application/UserLoginService.java
- src/main/java/com/programmers/dev/kream/user/domain/User.java
- src/main/java/com/programmers/dev/kream/user/domain/UserRepository.java
- src/main/java/com/programmers/dev/kream/user/ui/UserController.java
- src/main/resources/application.yml
- src/main/resources/sql/data.sql
> 스프링 시큐리티 환경 구축

- src/main/java/com/programmers/dev/kream/product/application/ProductService.java
- src/main/java/com/programmers/dev/kream/product/domain/ProductInfo.java
- src/main/java/com/programmers/dev/kream/product/domain/ProductRepository.java
- src/main/java/com/programmers/dev/kream/product/ui/ProductController.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/ProductUpdateRequest.java
- src/main/java/com/programmers/dev/kream/product/ui/dto/ProductUpdateResponse.java
- src/test/java/com/programmers/dev/kream/product/application/ProductServiceTest.java
- src/test/java/com/programmers/dev/kream/product/ui/ProductControllerTest.java
1️⃣ SizedProduct, Product 엔티티 병합 작업으로 인하여 사이즈만 다르고 동일한 제품의 정보 update 쿼리 구현
2️⃣ 제품 정보 수정 시 request dto 필드 수정
3️⃣ 제품 정보 수정 시 response dto record 생성
> Refactor: SizedProduct, Product 엔티티 병합 작업으로 인한 제품 update 리팩토링 [#64]

- src/main/java/com/programmers/dev/kream/sellorder/domain/SellOrder.java
- src/main/java/com/programmers/dev/kream/sellorder/domain/SellOrderRepository.java
즉시 판매 관련 테이블 생성 
즉시 판매 관련 Repository 생성
> Feat: 즉시 판매 관련 테이블 및 Repository 생성 [#49]

- module-domain/src/main/java/com/programmers/dev/bidding/domain/Bidding.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/BiddingRepository.java
Bidding 관련 Entity 및 Repository 생성
> Feat: 입찰 관련 Entity 및 Repository 생성 [#78]

- module-domain/src/main/java/com/programmers/dev/Auction/domain/Auction.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBidding.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBiddingRepository.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionRepository.java
- Auction, AuctionBidding 엔티티 및 Repository 생성하였습니다.
> Feat: Auction, AuctionBidding 엔티티 및 Repository생성 [#80]

- module-api/build.gradle
- module-domain/build.gradle
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/Auction.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/AuctionSaveRequest.java
- module-domain/src/main/java/com/programmers/dev/common/AuctionStatus.java
- module-domain/src/test/java/com/programmers/dev/Auction/application/AuctionServiceTest.java
- module-domain/src/test/java/com/programmers/dev/ModuleDomainApplicationTests.java
- 경매 등록 기능 구현 및 테스트 코드 작성하였습니다.
> [경매] 등록 기능 구현 및 테스트

- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/Auction.java
- module-domain/src/test/java/com/programmers/dev/Auction/application/AuctionServiceTest.java
- 경매 시작, 종료에 따른 상태 변경 기능 구현 및 테스트 작성하였습니다.
> Change status

- module-api/build.gradle
- module-api/src/main/docs/asciidoc/index.adoc
- module-api/src/main/java/com/programmers/dev/bidding/ui/BiddingController.java
- module-api/src/main/resources/application.yml
- module-api/src/test/java/com/programmers/dev/bidding/ui/BiddingControllerTest.java
- module-api/src/test/resources/application.yml
- module-domain/build.gradle
- module-domain/src/main/java/com/programmers/dev/bidding/application/BiddingService.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/Bidding.java
- module-domain/src/main/java/com/programmers/dev/bidding/dto/BiddingResponse.java
- module-domain/src/main/java/com/programmers/dev/bidding/dto/RegisterPurchaseBiddingRequest.java
- module-domain/src/test/java/com/programmers/dev/ModuleApiApplicationTest.java
- module-domain/src/test/java/com/programmers/dev/bidding/application/BiddingServiceTest.java
> Feat: [입찰] 구매 입찰 등록 구현 [#77, #78]

- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBidding.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/AuctionBidRequest.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/AuctionBidResponse.java
- module-domain/src/main/java/com/programmers/dev/exception/ErrorCode.java
- module-domain/src/test/java/com/programmers/dev/Auction/application/AuctionBiddingServiceTest.java
- 진행중인 경매에 대하여 입찰 기능을 구현하였습니다.
- 진행중이지 않은 경매에 대해서 입찰할 경우 예외가 발생합니다.
> Feat: 경매 입찰 기능 구현[#88]

- module-api/src/main/java/com/programmers/dev/bidding/ui/BiddingController.java
- module-api/src/test/java/com/programmers/dev/bidding/ui/BiddingControllerTest.java
- module-domain/src/main/java/com/programmers/dev/bidding/application/BiddingService.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/Bidding.java
- module-domain/src/main/java/com/programmers/dev/bidding/dto/TransactSellBiddingRequest.java
- module-domain/src/main/java/com/programmers/dev/common/Status.java
- module-domain/src/test/java/com/programmers/dev/bidding/application/BiddingServiceTest.java
- module-domain/src/test/resources/application.yml
> Feat: [입찰] 즉시 구매 구현 [#78, #87]

- module-api/src/main/java/com/programmers/dev/inventory/ui/InventoryController.java
- module-domain/src/main/java/com/programmers/dev/common/Status.java
- module-domain/src/main/java/com/programmers/dev/inventory/domain/ProductQuality.java
- module-domain/src/main/java/com/programmers/dev/inventory/domain/TransactionType.java
- module-domain/src/main/java/com/programmers/dev/inventory/dto/InventoryStoreRequest.java
- module-domain/src/main/java/com/programmers/dev/inventory/statechange/dto/InventoryStoreRequest.java
- module-domain/src/test/java/com/programmers/dev/ModuleDomainApplicationTests.java
> Status refactor

- module-api/build.gradle
- module-api/src/main/java/com/programmers/dev/Auction/ui/AuctionBiddingController.java
- module-api/src/test/java/com/programmers/dev/Auction/ui/AuctionBiddingControllerTest.java
- module-api/src/test/resources/application.yml
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/AuctionBidRequest.java
- module-domain/src/test/java/com/programmers/dev/Auction/application/AuctionBiddingServiceTest.java
- 진행중인 경매에 대한 입찰 api 구현 및 테스트 작성 하였습니다.
> 진행중인 경매에 대한 입찰 api 구현 및 테스트 작성 [#88]

- module-api/src/main/java/com/programmers/ModuleApiApplication.java
- module-api/src/main/java/com/programmers/dev/schedule/BiddingScheduler.java
- module-domain/src/main/java/com/programmers/dev/bidding/application/BiddingService.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/Bidding.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/BiddingRepository.java
- module-domain/src/main/java/com/programmers/dev/exception/ErrorCode.java
- module-domain/src/test/java/com/programmers/dev/bidding/application/BiddingServiceTest.java
입찰 마감 기한이 지났을 경우 입찰 마감 처리 기능 추가
> Feat: [입찰] 입찰 마감 처리 [#78, #100]

- module-api/src/main/java/com/programmers/dev/bidding/ui/BiddingController.java
- module-api/src/test/java/com/programmers/dev/bidding/ui/BiddingControllerTest.java
- module-domain/src/main/java/com/programmers/dev/bidding/application/BiddingService.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/BiddingRepository.java
- module-domain/src/main/java/com/programmers/dev/bidding/dto/RegisterBiddingRequest.java
- module-domain/src/main/java/com/programmers/dev/exception/ErrorCode.java
- module-domain/src/test/java/com/programmers/dev/bidding/application/BiddingServiceTest.java
- 구매 입찰 등록 -> 판매 입찰 등록된 금액보다 높은 금액으로 등록 시 에러 발생 
- 판매 입찰 등록 -> 구매 입찰 등록된 금액보다 높은 금액으로 등록 시 에러 발생
> Feat: [입찰] 경매 등록시 기존에 올라온 금액보다 높은 금액 설정시 오류 발생 처리 [#78, #106]

- module-domain/src/main/java/com/programmers/dev/transaction/application/TransactionService.java
- module-domain/src/main/java/com/programmers/dev/transaction/domain/Transaction.java
- module-domain/src/main/java/com/programmers/dev/transaction/domain/TransactionRepository.java
- module-domain/src/main/java/com/programmers/dev/transaction/domain/TransactionType.java
> Feat: 거래 정보를 저장하는 엔티티인 Transaction 관련 코드 구현 [#108]

- module-api/src/main/java/com/programmers/dev/Auction/ui/AuctionBiddingController.java
- module-api/src/test/java/com/programmers/dev/Auction/ui/AuctionBiddingControllerTest.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBiddingRepository.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/AuctionBiddingCancelRequest.java
- module-domain/src/test/java/com/programmers/dev/Auction/application/AuctionBiddingServiceTest.java
- 입찰 취소 기능 구현 및 테스트 작성 하였습니다.
- 입찰 취소 api 구현 및 테스트 작성하였습니다.
- 입찰 취소시 requestBody에 무엇을 전달받아 사용할지 고민하였는데 우선 경매 ID와 가격을 전달받는것으로 결정하였습니다.
> 입찰 취소 기능, api 구현 및 테스트 작성 [#102]

- module-api/src/main/java/com/programmers/dev/Auction/ui/AuctionBiddingController.java
- module-api/src/test/java/com/programmers/dev/Auction/ui/AuctionBiddingControllerTest.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBiddingRepository.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/BiddingPriceGetRequest.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/BiddingPriceGetResponse.java
- module-domain/src/test/java/com/programmers/dev/Auction/application/AuctionBiddingServiceTest.java
- 경매 ID를 통해 해당 경매의 현재 최고 입찰가 조회 기능 및 api 구현하였습니다.
- 경매 ID를 통해 해당 경매의 현재 최고 입찰가 조회 기능 및 api 테스트 작성하였습니다.
> 경매 ID를 통해 해당 경매의 현재 최고 입찰가 조회 [#103]

- module-api/src/main/docs/asciidoc/index.adoc
> Docs: adoc 문서 작성하였습니다.

- module-api/src/main/java/com/programmers/dev/inventory/ui/InventoryStateChangeController.java
- module-domain/src/main/java/com/programmers/dev/inventory/application/InventoryStateChangeService.java
- module-domain/src/main/java/com/programmers/dev/inventory/domain/Inventory.java
- module-domain/src/main/java/com/programmers/dev/inventory/domain/InventoryType.java
- module-domain/src/main/java/com/programmers/dev/inventory/dto/InventoryRegisterRequest.java
- module-domain/src/main/java/com/programmers/dev/inventory/dto/statechange/InventoryArrivedRequest.java
- module-domain/src/main/java/com/programmers/dev/transaction/application/TransactionService.java
- module-domain/src/main/java/com/programmers/dev/transaction/domain/Transaction.java
- module-domain/src/main/java/com/programmers/dev/transaction/domain/TransactionRepository.java
> Refactor: InventoryType 으로 변경

- module-api/src/main/java/com/programmers/dev/bidding/ui/BiddingController.java
- module-api/src/test/java/com/programmers/dev/bidding/ui/BiddingControllerTest.java
- module-domain/src/main/java/com/programmers/dev/bidding/application/BiddingService.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/Bidding.java
- module-domain/src/test/java/com/programmers/dev/bidding/application/BiddingServiceTest.java
> Feat: 구매 입찰 -> 배송 기능 추가 [#78, #116]

- module-api/src/main/docs/asciidoc/index.adoc
- module-api/src/main/java/com/programmers/dev/inventory/ui/InventoryStateChangeController.java
- module-api/src/test/java/com/programmers/dev/inventory/ui/InventoryRegisterControllerTest.java
- module-api/src/test/java/com/programmers/dev/inventory/ui/InventoryStateChangeControllerArrivedTest.java
- module-api/src/test/java/com/programmers/dev/inventory/ui/InventoryStateChangeControllerAuthenticationTest.java
- module-api/src/test/java/com/programmers/dev/inventory/ui/InventoryStateChangeControllerSetPriceTest.java
- module-domain/src/main/java/com/programmers/dev/inventory/dto/statechange/InventoryMultipleStateChangeResponse.java
- module-domain/src/main/java/com/programmers/dev/inventory/dto/statechange/InventorySingleStateChangeResponse.java
- 테스트 코드를 추가
- 보관판매 관련 adoc 파일 작성
> State controller response

- module-api/src/test/java/com/programmers/dev/bidding/ui/BiddingControllerTest.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBidding.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/AuctionSaveResponse.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/AuctionStatusChangeResponse.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/BiddingPriceGetRequest.java
- module-domain/src/main/java/com/programmers/dev/exception/ErrorCode.java
- 현재 입찰 최고가보다 낮은 금액은 입찰이 불가능하도록 설정
- 입찰이 없을 경우 최고가는 경매 시작가격을 반환
- 객체  생성을 Service에서 DTO로 책임 위임
> 경매 입찰 로직 고도화 [#133]

- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBidding.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBiddingRepository.java
- module-domain/src/main/java/com/programmers/dev/exception/ErrorCode.java
> 경매 상태 변경 로직 고도화

- module-domain/src/main/java/com/programmers/dev/bidding/application/BiddingService.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/Bidding.java
> Feat: Bidding 관련 로그 추가 [#78]

- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/Auction.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBidding.java
> Feat: Auction 관련 log 추가 [#143]

- module-api/src/main/java/com/programmers/dev/bidding/ui/BiddingController.java
- module-api/src/test/java/com/programmers/dev/bidding/ui/BiddingControllerTest.java
- module-domain/src/main/java/com/programmers/dev/bidding/application/BiddingService.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/Bidding.java
- module-domain/src/main/java/com/programmers/dev/exception/ErrorCode.java
- module-domain/src/main/java/com/programmers/dev/user/domain/User.java
- module-domain/src/test/java/com/programmers/dev/bidding/application/BiddingServiceTest.java
> Feat: 판매 거부 기능 구현 [#78, #148]

- module-api/src/main/docs/asciidoc/index.adoc
- module-api/src/main/java/com/programmers/dev/Auction/ui/AuctionBiddingController.java
- module-api/src/test/java/com/programmers/dev/Auction/ui/AuctionBiddingControllerTest.java
- module-api/src/test/java/com/programmers/dev/Auction/ui/AuctionControllerTest.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBiddingRepository.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/BidderDecisionRequest.java
- module-domain/src/main/java/com/programmers/dev/Auction/dto/BidderDecisionResponse.java
- module-domain/src/main/java/com/programmers/dev/common/AuctionStatus.java
- module-domain/src/test/java/com/programmers/dev/Auction/application/AuctionServiceTest.java
> 경매 종료에 따른 추가 로직 구현

- README.md
> Docs: README 초안 작성

- module-api/src/test/java/com/programmers/dev/bidding/ui/BiddingControllerTest.java
- module-domain/src/main/java/com/programmers/dev/bidding/application/BiddingService.java
- module-domain/src/main/java/com/programmers/dev/bidding/domain/Bidding.java
- module-domain/src/main/java/com/programmers/dev/common/Status.java
- module-domain/src/main/java/com/programmers/dev/exception/ErrorCode.java
- module-domain/src/test/java/com/programmers/dev/bidding/application/BiddingServiceTest.java
> Refactor: 검증 강화 및 리팩터링 [#78]

- module-api/src/main/java/com/programmers/dev/configuration/SecurityConfiguration.java
- module-api/src/main/java/com/programmers/dev/web/MyPageController.java
- module-api/src/main/java/com/programmers/dev/web/MyPageService.java
- module-api/src/main/resources/templates/myPage.html
- module-domain/src/main/java/com/programmers/dev/bidding/domain/BiddingRepository.java
- module-domain/src/main/java/com/programmers/dev/inventory/domain/InventoryRepository.java
- module-domain/src/main/java/com/programmers/dev/inventoryorder/domain/InventoryOrderRepository.java
> Feat: status 전용 화면 구현

- module-api/src/main/resources/application.yml
- module-domain/build.gradle
- module-domain/src/main/java/com/programmers/dev/banking/aop/BankingLoggingAspect.java
- module-domain/src/main/java/com/programmers/dev/exception/CreamExceptionHandler.java
SLACK 을 통한 알람이 필요하다고 생각하는 예외에 대해 Sentry 를 적용했습니다.
- INTERNAL_SERVER_ERROR 500 ERROR
- BankingException
> Feat: 500 Internal Error, BankingService 에러 발생시 Sentry 작동

- module-api/src/test/java/com/programmers/dev/Auction/ui/AuctionControllerTest.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionBiddingService.java
- module-domain/src/main/java/com/programmers/dev/Auction/application/AuctionService.java
- module-domain/src/main/java/com/programmers/dev/Auction/domain/AuctionBiddingRepository.java
- 입찰자가 구매 결정 시 구매자 계죄에서 금액 차감
- 경매 종료시 세번째 입찰가부터 데이터 삭제
> 경매 기능 추가 PR
